version: "2.0" 
services:

        db:
          image: mysql:5.7 
          container_name: mysql
          env_file:
               - ./mysql.env

        web:
          build: .
          container_name: web
          ports:
               - 80:5000
          volumes:
               - .:/app
 
